### ISSUE TITLE
COMBS Documentation

### ISSUE THREAD

**Issue by flrlucas** [npolizzi/Combs#17]
Is there an updated version of the library available, and/or is the documentation update still in the works?

**Comment by npolizzi** [comment]
I have a new repo called Combs2 that has updated code, libraries, and some unpublished new features. Let me know if you'd like to use that. It has some documentation (though not much) and a fairly decent tutorial. The plan is to make the Combs2 repo public once we publish the paper / submit the preprint.

**Comment by flrlucas** [comment]
Thank you for the reply.
I would love to have a look, but given the unpublished nature I understand the hold-back.

Perhaps you would have some time for a private chat, as we are looking for the applicability in some future research lines.
